# Generated by Django 2.0.1 on 2020-05-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nome do Grupo')),
                ('coleader', models.CharField(max_length=35, verbose_name='Trainee')),
                ('cell_type', models.CharField(choices=[('H', 'Homens'), ('M', 'Mulheres'), ('J', 'Jovens'), ('C', 'Moças')], max_length=1, verbose_name='Célula de')),
                ('created_at', models.DateField(verbose_name='Data de Abertura')),
                ('meeting_day', models.TextField(choices=[('DM', 'Domingo'), ('SF', 'Segunda-feira '), ('TF', 'Terça-feira '), ('QF', 'Quarta-feira  '), ('QT', 'Quinta feira '), ('SF', 'Sexta-feira'), ('SB', 'Sábado')], verbose_name='Dia da Reunião')),
                ('uf', models.CharField(blank=True, choices=[('', 'Estado'), ('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MT', 'Mato Grosso'), ('MA', 'Maranhão'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RS', 'Rio Grande do Sul'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Cidade')),
                ('street', models.CharField(blank=True, max_length=100, verbose_name='Rua')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='Numero')),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
            ],
            options={
                'verbose_name': 'Celula',
                'verbose_name_plural': 'Celulas',
            },
        ),
        migrations.CreateModel(
            name='Evasao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True, unique=True, verbose_name='Nome*')),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True, verbose_name='Sexo*')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='Data de nascimento*')),
                ('ladder', models.CharField(blank=True, choices=[('N0', 'Novo Convertido'), ('N1', 'Cursando-N1'), ('N2', 'Cursando-N2'), ('N3', 'Cursando-N3'), ('N4', 'Cursando-Trainee'), ('N5', 'Trainee Formado'), ('LC', 'Lider de Célula'), ('LG', 'Lider de Geração'), ('PR', 'Pastores')], max_length=2, null=True, verbose_name='Escada do Sucesso*')),
                ('date_conversion', models.DateField(blank=True, null=True, verbose_name='Data da Conversão')),
                ('meeting_date', models.DateField(blank=True, null=True, verbose_name='Data Do Encontro')),
                ('date_batismo', models.DateField(blank=True, null=True, verbose_name='Data Do Batismo')),
                ('consolidator', models.CharField(blank=True, max_length=40, verbose_name='Consolidador')),
                ('date_delete', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=40, verbose_name='Motivo*')),
            ],
        ),
    ]
