# Generated by Django 2.0.1 on 2020-05-27 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evasao',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Leader'),
        ),
        migrations.AddField(
            model_name='celula',
            name='leader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.Leader'),
        ),
    ]
