# Generated by Django 2.1 on 2020-05-25 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200523_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='celula',
            old_name='celula_de',
            new_name='cell_type',
        ),
        migrations.RenameField(
            model_name='celula',
            old_name='cidade',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='celula',
            old_name='colider',
            new_name='coleader',
        ),
        migrations.RenameField(
            model_name='celula',
            old_name='criado_em',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='celula',
            old_name='lider',
            new_name='leader',
        ),
        migrations.RenameField(
            model_name='celula',
            old_name='dia_reuniao',
            new_name='meeting_day',
        ),
        migrations.RenameField(
            model_name='celula',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='celula',
            old_name='bairro',
            new_name='neighborhood',
        ),
        migrations.RenameField(
            model_name='celula',
            old_name='numero',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='celula',
            old_name='rua',
            new_name='street',
        ),
    ]
