# Generated by Django 2.0.1 on 2020-05-26 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200524_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evasao',
            old_name='nascimento',
            new_name='birth',
        ),
        migrations.RenameField(
            model_name='evasao',
            old_name='consolidador',
            new_name='consolidator',
        ),
        migrations.RenameField(
            model_name='evasao',
            old_name='data_batismo',
            new_name='date_batismo',
        ),
        migrations.RenameField(
            model_name='evasao',
            old_name='data_encontro',
            new_name='date_contrace',
        ),
        migrations.RenameField(
            model_name='evasao',
            old_name='data_conversao',
            new_name='date_conversion',
        ),
        migrations.RenameField(
            model_name='evasao',
            old_name='lider',
            new_name='leader',
        ),
        migrations.RenameField(
            model_name='evasao',
            old_name='tipo',
            new_name='ministerial_situation',
        ),
        migrations.RenameField(
            model_name='evasao',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='evasao',
            old_name='motivo',
            new_name='reason',
        ),
        migrations.RenameField(
            model_name='evasao',
            old_name='sexo',
            new_name='sex',
        ),
    ]
