# Generated by Django 2.0.1 on 2020-05-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200527_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='celula',
            name='cep',
            field=models.CharField(default=1, max_length=10, verbose_name='CEP'),
            preserve_default=False,
        ),
    ]
