# Generated by Django 2.0.1 on 2020-05-26 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200525_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evasao',
            old_name='date_contrace',
            new_name='meeting_date',
        ),
    ]
