# Generated by Django 2.1.5 on 2019-03-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190319_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='lider',
            name='tipo',
            field=models.CharField(blank=True, choices=[('LC', 'Lider de Célula'), ('LG', 'Lider de Geração'), ('PR', 'Pastores')], max_length=2, verbose_name='Tipo*'),
        ),
    ]
