# Generated by Django 2.1.5 on 2019-03-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190321_2106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
        migrations.AddField(
            model_name='discipulo',
            name='data_conversao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Conversão'),
        ),
        migrations.AddField(
            model_name='discipulo',
            name='endereco',
            field=models.CharField(blank=True, max_length=50, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='discipulo',
            name='escolaridade',
            field=models.CharField(blank=True, choices=[('ANF', 'Analfabeto'), ('EFI', 'Ensino fundamental incompleto'), ('EFC', 'Ensino fundamental completo'), ('EMI', 'Ensino médio incompleto'), ('EMC', 'Ensino médio completo'), ('ESC', 'Superior completo'), ('PGC', 'Pós-Graduação'), ('MES', 'Mestrado'), ('DOT', 'Doutorado')], max_length=3),
        ),
        migrations.AddField(
            model_name='discipulo',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telefone/Cel'),
        ),
        migrations.AddField(
            model_name='lider',
            name='data_conversao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Conversão'),
        ),
        migrations.AddField(
            model_name='lider',
            name='endereco',
            field=models.CharField(blank=True, max_length=50, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='lider',
            name='escolaridade',
            field=models.CharField(blank=True, choices=[('ANF', 'Analfabeto'), ('EFI', 'Ensino fundamental incompleto'), ('EFC', 'Ensino fundamental completo'), ('EMI', 'Ensino médio incompleto'), ('EMC', 'Ensino médio completo'), ('ESC', 'Superior completo'), ('PGC', 'Pós-Graduação'), ('MES', 'Mestrado'), ('DOT', 'Doutorado')], max_length=3),
        ),
        migrations.AddField(
            model_name='lider',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telefone/Cel'),
        ),
    ]
