# Generated by Django 2.1 on 2019-04-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190326_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discipulo',
            old_name='endereco',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='lider',
            old_name='endereco',
            new_name='cidade',
        ),
        migrations.AddField(
            model_name='discipulo',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='discipulo',
            name='cep',
            field=models.CharField(blank=True, max_length=20, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='discipulo',
            name='complemento',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='discipulo',
            name='consolidador',
            field=models.CharField(blank=True, max_length=40, verbose_name='Consolidador'),
        ),
        migrations.AddField(
            model_name='discipulo',
            name='data_batismo',
            field=models.DateField(blank=True, null=True, verbose_name='Data Do Batismo'),
        ),
        migrations.AddField(
            model_name='discipulo',
            name='data_encontro',
            field=models.DateField(blank=True, null=True, verbose_name='Data Do Encontro'),
        ),
        migrations.AddField(
            model_name='discipulo',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='discipulo',
            name='numero',
            field=models.CharField(blank=True, max_length=100, verbose_name='Numero'),
        ),
        migrations.AddField(
            model_name='discipulo',
            name='profissao',
            field=models.CharField(blank=True, help_text='Digite sua Ocupação', max_length=40, verbose_name='Profissão'),
        ),
        migrations.AddField(
            model_name='discipulo',
            name='rua',
            field=models.CharField(blank=True, max_length=100, verbose_name='Rua'),
        ),
        migrations.AddField(
            model_name='discipulo',
            name='uf',
            field=models.CharField(blank=True, choices=[('', 'Escolha uma Opção'), ('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MT', 'Mato Grosso'), ('MA', 'Maranhão'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RS', 'Rio Grande do Sul'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='lider',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='lider',
            name='cep',
            field=models.CharField(blank=True, max_length=20, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='lider',
            name='complemento',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lider',
            name='consolidador',
            field=models.CharField(blank=True, max_length=40, verbose_name='Consolidador'),
        ),
        migrations.AddField(
            model_name='lider',
            name='data_batismo',
            field=models.DateField(blank=True, null=True, verbose_name='Data Do Batismo'),
        ),
        migrations.AddField(
            model_name='lider',
            name='data_encontro',
            field=models.DateField(blank=True, null=True, verbose_name='Data Do Encontro'),
        ),
        migrations.AddField(
            model_name='lider',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='lider',
            name='numero',
            field=models.CharField(blank=True, max_length=100, verbose_name='Numero'),
        ),
        migrations.AddField(
            model_name='lider',
            name='profissao',
            field=models.CharField(blank=True, help_text='Digite sua Ocupação', max_length=40, verbose_name='Profissão'),
        ),
        migrations.AddField(
            model_name='lider',
            name='rua',
            field=models.CharField(blank=True, max_length=100, verbose_name='Rua'),
        ),
        migrations.AddField(
            model_name='lider',
            name='uf',
            field=models.CharField(blank=True, choices=[('', 'Escolha uma Opção'), ('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MT', 'Mato Grosso'), ('MA', 'Maranhão'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RS', 'Rio Grande do Sul'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='discipulo',
            name='tipo',
            field=models.CharField(blank=True, choices=[('N0', 'Novo Convertido'), ('N1', 'Cursando-N1'), ('N2', 'Cursando-N2'), ('N3', 'Cursando-N3'), ('N4', 'Cursando-Trainee'), ('N5', 'Trainee Formado'), ('LC', 'Lider de Célula'), ('LG', 'Lider de Geração'), ('PR', 'Pastores')], max_length=2, null=True, verbose_name='Situação Ministerial*'),
        ),
        migrations.AlterField(
            model_name='lider',
            name='tipo',
            field=models.CharField(blank=True, choices=[('N0', 'Novo Convertido'), ('N1', 'Cursando-N1'), ('N2', 'Cursando-N2'), ('N3', 'Cursando-N3'), ('N4', 'Cursando-Trainee'), ('N5', 'Trainee Formado'), ('LC', 'Lider de Célula'), ('LG', 'Lider de Geração'), ('PR', 'Pastores')], max_length=2, null=True, verbose_name='Situação Ministerial*'),
        ),
    ]
