# Generated by Django 2.1 on 2019-04-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_evasao'),
    ]

    operations = [
        migrations.AddField(
            model_name='evasao',
            name='motivo',
            field=models.CharField(default='nao sabne', max_length=40, verbose_name='Motivo*'),
            preserve_default=False,
        ),
    ]
