# Generated by Django 2.1 on 2019-04-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190408_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipulo',
            name='saiu',
            field=models.CharField(blank=True, max_length=40, verbose_name='Motivo*'),
        ),
        migrations.AddField(
            model_name='lider',
            name='saiu',
            field=models.CharField(blank=True, max_length=40, verbose_name='Motivo*'),
        ),
    ]
