# Generated by Django 2.1 on 2019-05-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190415_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celula',
            name='celula_de',
            field=models.CharField(choices=[('H', 'Homens'), ('M', 'Mulheres'), ('J', 'Jovens'), ('C', 'Moças')], max_length=1, verbose_name='Célula de'),
        ),
    ]
