# Generated by Django 2.2.3 on 2020-02-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_igreja'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Igreja',
        ),
        migrations.AlterField(
            model_name='celula',
            name='nome',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nome do Grupo'),
        ),
        migrations.AlterField(
            model_name='discipulo',
            name='nome',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Nome*'),
        ),
        migrations.AlterField(
            model_name='lider',
            name='nome',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Nome*'),
        ),
    ]
