# Generated by Django 2.2.3 on 2020-02-17 23:20

from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base
import igrejas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Igreja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Igreja/Cliente')),
                ('pago_ate', models.DateField(blank=True, default=igrejas.models.one_month_from_today, null=True, verbose_name='Pago Até')),
                ('on_trial', models.BooleanField(default=True, verbose_name='Em Teste')),
                ('criado_em', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='igrejas.Igreja')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
