# Generated by Django 2.0.1 on 2020-05-27 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True, verbose_name='Nome*')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True, verbose_name='Sexo*')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='Data de nascimento*')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=15, verbose_name='Telefone/Cel')),
                ('facebook', models.CharField(blank=True, max_length=50, verbose_name='Facebook')),
                ('ministry', models.CharField(blank=True, choices=[('N0', 'Novo Convertido'), ('N1', 'Cursando-N1'), ('N2', 'Cursando-N2'), ('N3', 'Cursando-N3'), ('N4', 'Cursando-Trainee'), ('N5', 'Trainee Formado'), ('LC', 'Lider de Célula'), ('LG', 'Lider de Geração'), ('PR', 'Pastores')], max_length=2, null=True, verbose_name='Situação Ministerial*')),
                ('conversion_date', models.DateField(blank=True, null=True, verbose_name='Data da Conversão')),
                ('meeting_date', models.DateField(blank=True, null=True, verbose_name='Data Do Encontro')),
                ('date_batismo', models.DateField(blank=True, null=True, verbose_name='Data Do Batismo')),
                ('consolidator', models.CharField(blank=True, max_length=40, verbose_name='Consolidador')),
                ('schooling', models.CharField(blank=True, choices=[('ANF', 'Não Alfabetizado'), ('EFI', 'Ensino fundamental incompleto'), ('EFC', 'Ensino fundamental completo'), ('EMI', 'Ensino médio incompleto'), ('EMC', 'Ensino médio completo'), ('ESC', 'Superior completo'), ('PGC', 'Pós-Graduação'), ('MES', 'Mestrado'), ('DOT', 'Doutorado')], max_length=3)),
                ('profession', models.CharField(blank=True, help_text='Digite sua Ocupação', max_length=40, verbose_name='Profissão')),
                ('uf', models.CharField(blank=True, choices=[('', 'Estado'), ('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MT', 'Mato Grosso'), ('MA', 'Maranhão'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RS', 'Rio Grande do Sul'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Cidade')),
                ('street', models.CharField(blank=True, max_length=100, verbose_name='Rua')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='Numero')),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('complement', models.CharField(blank=True, max_length=50)),
                ('cep', models.CharField(blank=True, max_length=20, verbose_name='CEP')),
                ('exited', models.CharField(blank=True, max_length=40, null=True, verbose_name='Motivo*')),
                ('celula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Celula')),
            ],
            options={
                'verbose_name': 'Discipulo',
                'verbose_name_plural': 'Discipulos',
            },
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True, verbose_name='Nome*')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True, verbose_name='Sexo*')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='Data de nascimento*')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=15, verbose_name='Telefone/Cel')),
                ('facebook', models.CharField(blank=True, max_length=50, verbose_name='Facebook')),
                ('ministry', models.CharField(blank=True, choices=[('N0', 'Novo Convertido'), ('N1', 'Cursando-N1'), ('N2', 'Cursando-N2'), ('N3', 'Cursando-N3'), ('N4', 'Cursando-Trainee'), ('N5', 'Trainee Formado'), ('LC', 'Lider de Célula'), ('LG', 'Lider de Geração'), ('PR', 'Pastores')], max_length=2, null=True, verbose_name='Situação Ministerial*')),
                ('conversion_date', models.DateField(blank=True, null=True, verbose_name='Data da Conversão')),
                ('meeting_date', models.DateField(blank=True, null=True, verbose_name='Data Do Encontro')),
                ('date_batismo', models.DateField(blank=True, null=True, verbose_name='Data Do Batismo')),
                ('consolidator', models.CharField(blank=True, max_length=40, verbose_name='Consolidador')),
                ('schooling', models.CharField(blank=True, choices=[('ANF', 'Não Alfabetizado'), ('EFI', 'Ensino fundamental incompleto'), ('EFC', 'Ensino fundamental completo'), ('EMI', 'Ensino médio incompleto'), ('EMC', 'Ensino médio completo'), ('ESC', 'Superior completo'), ('PGC', 'Pós-Graduação'), ('MES', 'Mestrado'), ('DOT', 'Doutorado')], max_length=3)),
                ('profession', models.CharField(blank=True, help_text='Digite sua Ocupação', max_length=40, verbose_name='Profissão')),
                ('uf', models.CharField(blank=True, choices=[('', 'Estado'), ('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MT', 'Mato Grosso'), ('MA', 'Maranhão'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RS', 'Rio Grande do Sul'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Cidade')),
                ('street', models.CharField(blank=True, max_length=100, verbose_name='Rua')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='Numero')),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('complement', models.CharField(blank=True, max_length=50)),
                ('cep', models.CharField(blank=True, max_length=20, verbose_name='CEP')),
                ('exited', models.CharField(blank=True, max_length=40, null=True, verbose_name='Motivo*')),
                ('lider_de_rede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liderado', to='members.Leader', verbose_name='Leader*')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leader',
                'verbose_name_plural': 'Lideres',
            },
        ),
        migrations.AddField(
            model_name='discipulo',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Leader'),
        ),
    ]
