# Generated by Django 2.0.1 on 2020-05-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20200527_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discipulo',
            old_name='celula',
            new_name='cell',
        ),
        migrations.AlterField(
            model_name='discipulo',
            name='ladder',
            field=models.CharField(blank=True, choices=[('N0', 'Novo Convertido'), ('N1', 'Cursando-N1'), ('N2', 'Cursando-N2'), ('N3', 'Cursando-N3'), ('N4', 'Cursando-Trainee'), ('N5', 'Trainee Formado')], max_length=2, null=True, verbose_name='Escada do Sucesso*'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='ladder',
            field=models.CharField(blank=True, choices=[('N0', 'Novo Convertido'), ('N1', 'Cursando-N1'), ('N2', 'Cursando-N2'), ('N3', 'Cursando-N3'), ('N4', 'Cursando-Trainee'), ('N5', 'Trainee Formado')], max_length=2, null=True, verbose_name='Escada do Sucesso*'),
        ),
    ]
