# Generated by Django 2.0.1 on 2020-05-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20200527_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipulo',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='leader',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
